name: Deploy development build

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APK_PATH: "app/build/outputs/apk/debug/app-debug.apk"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generate local properties
        run: |
          touch local.properties
          touch prod.properties
#      - name: Run Tests
#        run: ./gradlew test
      - name: Build Debug APK
        run: ./gradlew app:assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.APK_PATH }}

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

        run: |
          npm install -g firebase-tools
          firebase --version
          firebase appdistribution:distribute "${{ env.APK_PATH }}" \
            --app "$FIREBASE_APP_ID" \
            --release-notes "$COMMIT_MESSAGE" \
            --groups "trusted-testers"