name: Deploy development build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy:
        required: true
        type: boolean

env:
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

  APK_PATH: ${{ vars.APK_PATH }}
  MEAL_API_URL: ${{ vars.MEAL_API_URL }}
  MEAL_API_KEY: ${{ secrets.MEAL_API_KEY }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate local properties
        run: |
          touch local.properties
          touch prod.properties

      - name: Save setup artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup-artifact
          path: .

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download setup artifact
        uses: actions/download-artifact@v4
        with:
          name: setup-artifact
          path: .

      - name: Set executable permission for Gradle
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

  build:
    if: inputs.deploy
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: test
    steps:
      - name: Download setup artifact
        uses: actions/download-artifact@v4
        with:
          name: setup-artifact
          path: .

      - name: Set executable permission for Gradle
        run: chmod +x gradlew

      # TODO Make dynamic
      - name: Build Debug APK
        run: ./gradlew app:assembleDebug

  deploy:
    if: inputs.deploy
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: $APK_PATH

      - name: Deploy to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          npm install -g firebase-tools
          firebase --version
          firebase appdistribution:distribute "$APK_PATH" \
            --app "$FIREBASE_APP_ID" \
            --release-notes "$COMMIT_MESSAGE" \
            --groups "trusted-testers"